---
# tasks file for perfsonar-archive

# Configure the measurements from remote templates
- name: Add authorised IP addresses to the archiver
  command: /usr/sbin/esmond_manage add_user_ip_address example_user "{{ item }}"
  with_items: "{{ perfsonar_psconfig_publish | default([]) }}"
